## 异常类的定义

## 一、实验说明
### 1.1 实验内容
本节作为 Web 框架 实现的最后一个模块


### 1.2 涉及知识点
* `异常处理`


### 1.3 实验环境
* `Python3`
* `Xfce` 终端
* `Sublimt` 编辑器

### 1.4 实验流程
* 理清需要的异常模块有哪一些
* 实现异常并在对应的地方抛出
* 实现异常捕获器和自定义异常装饰器
* 实战异常处理的用法

## 二、`Web 框架` 中的异常处理
在 `Web 应用` 中，异常大概可以分为两种，客户端异常和服务端异常，而这里我们是实现 `Web 框架`，所以我们只针对服务端异常。

服务端的异常有很多种，而在我们这个框架中可能出现的异常包括 `URL` 不存在，静态资源不存，请求方法不支持，业务逻辑中出现错误等，所以这一次要实现的异常处理模块，就是针对框架中可能会触发的错误进行捕获然后处理，让它在大多数情况下都可以正常使用。

## 三、实现异常处理模块
### 3.1 定义常见的异常
对于一个框架中可以预见到的错误，毫无疑问最清楚的人就是框架的实现者，而在前面的章节中，我们已经把功能模块都实现完了，所以同学们自己应该也能够想到有一些可能会触发错误的场景，由于是预见性的异常处理，框架没有在实际场景中大量使用，还有一些隐性的异常没找出来，所以没办法做到完整罗列，下面是我根据自己的理解，对能预见到的异常做进行罗列，并解释为什么我会认为对应的地方会触发这些异常，这样同学们也可以根据自己的理解，再次对异常处理模块做扩展，使框架的健壮性越来越高，下面就来看看我罗列出来的异常吧，代码定义在 `exceptions` 包中
```python
# 框架异常基类
class SYLFkException(Exception):
    def __init__(self, code='', message='Error'):
        self.code = code        # 异常编号
        self.message = message  # 异常信息

    def __str__(self):
        return self.message     # 当作为字符串使用时，返回异常信息


# 节点已存在存在
class EndpointExistsError(SYLFkException):
    def __init__(self, message='Endpoint exists'):
        super(EndpointExistsError, self).__init__(message)


# URL 已存在异常
class URLExistsError(SYLFkException):
    def __init__(self, message='URL exists'):
        super(URLExistsError, self).__init__(message)


# 文件未找到
class FileNotExistsError(SYLFkException):
    pass


# 权限不足
class RequireReadPermissionError(SYLFkException):
    pass


# 不支持的请求方法
class InvalidRequestMethodError(SYLFkException):
    pass


# 页面未找到
class PageNotFoundError(SYLFkException):
    pass


# 未知处理类型
class UnknownFuncError(SYLFkException):
    pass
```
先从三个已经实现好的异常开始讲解吧，这三个异常是我们在前面的章节中有使用到的，分别是一个异常基类，节点已存在异常和 `URL` 已存在异常，异常基类时所有异常的父类，是为框架所抛出的异常做的一个分类，这样在捕获异常的时候，就可以通过只捕获 `SYLFkException` 来过滤出框架自己抛出的异常而不需要使用 `Exception` 这个所有异常的父类了，方便我们自定义异常的处理。

在 `SYLFkException` 中有两个成员，分别是 `code` 和 `message`，顾名思义，一个是异常编号和异常信息，而我们后续继承它的异常就是通过实现不同的 `code` 和 `message` 来对不同异常进行识别并做对应的处理，而这里可以看到先实现的这两个异常的异常编号都为空，是因为后面的异常处理会忽略编号为空的异常，让它继续抛出，而这些编号为空的异常都是对框架启动或者正常工作有致命逻辑错误的，所以只能抛出它让开发者自己在代码层中进行修复。

接着看下面的 `FileNotExistsError` 文件不存在异常，还记得我们之前开发过的文件下载模块么，它是从服务端返回一个文件并提示浏览器进行下载，但是如果这个文件不存在于服务端，我们之前的做法是返回一个 `404 页面`，但是这样其实语义是不对的，因为 `404` 太笼统，还有可能是 `URL` 不存在等原因，所以这里把它单独抛出来，实现代码如下
```python
# 文件未找到
class FileNotExistsError(SYLFkException):
    def __init__(self, code='2', message='File not found'):
        super(FileNotExistsError, self).__init__(code, message)
```

这里我给他的异常编号是 2，它的由来是因为当读取一个不存在的文件时，`Python` 会抛出一个 `Error 2` 的 `Exception`，所以这里我就沿用了 2 这个编号，然后在框架主体文件中的 `render_file` 方法做一下修改，把最后的 `return` 改成抛出异常代码如下
```python
import sylfk.exceptions as exceptions

...
# 返回让客户端保存文件到本地的响应体
def render_file(file_path, file_name=None):
    ...

    # 如果不存在该文件，抛出文件不存在异常
    raise exceptions.FileNotExistsError
```

在这个方法中，其实还有一个可能会错的地方，就是当读取一个没有读取权限的文件时，会出现异常，所以就有了 `RequireReadPermissionError` 这个权限不足异常，实现如下
```python
# 权限不足
class RequireReadPermissionError(SYLFkException):
    def __init__(self, code='13', message='Require read permission'):
        super(RequireReadPermissionError, self).__init__(code, message)
```

异常编号思路同上，再回到 `render_file` 方法中修改判断逻辑，代码如下
```python
# 返回让客户端保存文件到本地的响应体
def render_file(file_path, file_name=None):

    # 判断服务器是否有该文件，抛出文件不存在异常
    if os.path.exists(file_path):

        # 判断是否有读取权限，没有则抛出权限不足异常
        if not os.access(file_path, os.R_OK):
            raise exceptions.RequireReadPermissionError
        ...
```

下一步就是 `InvalidRequestMethodError` 这个不支持的请求方法异常了，当客户端发向服务端的某个 `URL` 发起了一个该 `URL` 不支持的请求方法是抛出，它的异常编号我给的则是 `HTTP 协议` 中语义相近的 `401` 状态码，把 401 作为编号，定义如下
```python
# 不支持的请求方法
class InvalidRequestMethodError(SYLFkException):
    def __init__(self, code='401', message='Unknown or unsupported request method'):
        super(InvalidRequestMethodError, self).__init__(code, message)
```
对应的在框架主体的 `dispatch_request` 路由中判断请求方法的逻辑块里做修改，如下
```python
...

# 我这里以实验楼名字缩写命名框架名字： “实验楼 Framework”
class SYLFk:
    ...

    # URL 路由
    def dispatch_request(self, request):
        ...

        # 判断执行函数类型
        if exec_function.func_type == 'route':
            """ 路由处理 """

            # 判断请求方法是否支持
            if request.method in exec_function.options.get('methods'):
                ...
            else:
                """ 未知请求方法 """

                # 抛出请求方法不支持异常
                raise exceptions.InvalidRequestMethodError
        ...
```

紧接着的是在 `dispatch_request` 中的另一个容易出现异常的地方，当 `URL` 在映射关系中没找到时，我们原先是返回 `404` 响应体的那个逻辑块。同理其他原先也返回 `404` 响应体的地方都要改，比如 `dispatch_static` 方法中也用到了，都改为抛出 `PageNotFoundError` 异常，异常实现如下，代码定义在 `exceptions` 包中
```python
# URL 未找到
class PageNotFoundError(SYLFkException):
    def __init__(self, code='404', message='Source not found'):
        super(PageNotFoundError, self).__init__(code, message)
```
这个异常的编号定义思路同上，不再赘述，下面是两个方法的修改方式
```python
...

# 我这里以实验楼名字缩写命名框架名字： “实验楼 Framework”
class SYLFk:
    ...

    # 静态资源调路由
    def dispatch_static(self, static_path):
        ...

        # 判断资源文件是否在静态资源规则中，如果不存在，抛出页面未找到异常
        if static_path in self.static_map:
            ...
        else:
            # 抛出页面未找到异常
            raise exceptions.PageNotFoundError

    # URL 路由
    def dispatch_request(self, request):
        ...

        # 如果节点为空，抛出页面未找到异常
        if endpoint is None:
            raise exceptions.PageNotFoundError

        ...
```

最后一个异常 `UnknownFuncError` 是为框架设计的，也在 `dispatch_request` 方法中，原先返回 `503` 响应体那个地方，改为抛出未知处理类型，异常实现如下
```python 
# URL 未知处理类型
class UnknownFuncError(SYLFkException):
    def __init__(self, code='503', message='Unknown function type'):
        super(UnknownFuncError, self).__init__(code, message)
```
异常编号思路同上，然后就是更改 `dispatch_request` 方法，把原先返回 `503` 响应体的地方换成抛出未知处理类型异常，代码如下
```python
# 我这里以实验楼名字缩写命名框架名字： “实验楼 Framework”
class SYLFk:
    ...

    # URL 路由
    def dispatch_request(self, request):
        ...

        # 判断执行函数类型
        if exec_function.func_type == 'route':
            ...
        else:
            """ 未知类型处理 """

            # 抛出未知处理类型异常
            raise exceptions.UnknownFuncError
```

至此，我们的框架能预见的异常已经实现并且在对应的地方抛出，原先定义在框架主体中的 `ERROR_MAP` 框架主体已经没有直接使用到了，而我们的 `execeptions` 包就是之后使用它的主体，最后把它移动到 `exceptions` 包中，并且为上面新加的异常编号 `2` 和 `13` 绑定了对应的响应体，到这我们的异常定义就算完成了
```python
from werkzeug.wrappers import Response

# 定义公用的报头参数 Content-Type 
content_type = 'text/html; charset=UTF-8'

# 异常编号与响应体的映射关系
ERROR_MAP = {
    '2': Response('<h1>E2 Not Found File</h1>', content_type=content_type, status=500),
    '13': Response('<h1>E13 No Read Permission</h1>', content_type=content_type, status=500),
    '401': Response('<h1>401 Unknown Or Unsupported Method</h1>', content_type=content_type, status=401),
    '404': Response('<h1>404 Source Not Found<h1>', content_type=content_type, status=404),
    '503': Response('<h1>503 Unknown Function Type</h1>', content_type=content_type, status=503)
}
...
```

下面我们就来实现对这些异常的捕获并进行处理吧。

### 3.2 异常捕获处理
到了这里有的同学可能对捕获会有想法了，没错，异常捕获的思路跟数据库模块的 `DBResult` 中的 `capture` 装饰器思路是一样的，就是实现一个异常捕获装饰器，把被装饰的方法放在内部执行，捕获执行过程中的异常，不过这次多了一个捕获之后的处理，代码如下，定义在 `exceptions` 包中
```python
...

# 异常捕获
def capture(f):
    def decorator(*args, **options):
        # 开始捕获异常
        try:
            # 尝试执行函数
            rep = f(*args, **options)
        except SYLFkException as e:
            # 当捕获到 SYLFkException 这个分类的异常时，判断下异常的编号，如果不为空且关联再 ERROR_MAP 中，进行对应的处理，反之接着抛出
            if e.code in ERROR_MAP and ERROR_MAP[e.code]:

                # 获取异常关联的结果
                rep = ERROR_MAP[e.code]

                # 如果异常编号小于 100，响应状态码统一设置为 500 服务端错误
                status = int(e.code) if int(e.code) >= 100 else 500

                # 判断结果是否一个响应体，如果不是，则应该就是自定义异常处理函数，调用它并封装为响应体返回
                return rep if isinstance(rep, Response) or rep is None else Response(rep(), content_type=content_type, status=status)
            else:
                # 接着抛出没有对应处理的异常
                raise e
        # 返回函数执行正常的结果
        return rep
    # 返回装饰器
    return decorator
```
它的逻辑与 `DBResult` 中的 `capture` 没什么大区别，倒是有一个新概念，那就是自定义异常处理。目前框架抛出的异常所对应的处理都是我们作为框架开发者与定义的，但实际开发中，开发者可能要根据不同应用场景实现不同的处理，这也是我从始自终都在强调的一点，低耦合，高灵活度，而因为这里我预留的自定义逻辑处理是个函数，所以要暴露出一个接口供开发者去使用，下一步就来实现这个接口，它也是个装饰器。

### 3.3 自定义异常处理逻辑
这个装饰器的代码很短，如下，定义在 `exeception` 中
```python
...

# 异常处理重载装饰器，参数为异常编号，需要注意的是这里的编号为了方便开发者所以用的是整形
def reload(code):
    def decorator(f):
        # 替换 ERROR_MAP 中 异常编号关联的处理逻辑为所装饰的函数
        ERROR_MAP[str(code)] = f

    # 返回装饰器
    return decorator
```
思路其实就是替换掉原先异常编号绑定的对应处理而已，暴露这个装饰器的核心需求只是为开发者提供便利，下一步我们就把异常捕获装饰器结合到框架主体中吧。

### 3.4、组合到框架中
在框架主体中，凡是有抛出 `SYLFkException` 这个分类的异常的地方都需要被异常捕获器装饰，一共有四个方法 `add_url_rule`，`dispatch_static`，`dispatch_request` 和 `render_file`，把装饰器加上酒完成结合了
```python
...

# 我这里以实验楼名字缩写命名框架名字： “实验楼 Framework”
class SYLFk:
    ...

    # 添加路由规则
    @exceptions.capture
    def add_url_rule(self, url, func, func_type, endpoint=None, **options):
        ...

    # 静态资源调路由
    @exceptions.capture
    def dispatch_static(self, static_path):
        ...

    # URL 路由
    @exceptions.capture
    def dispatch_request(self, request):
        ...

...

# 返回让客户端保存文件到本地的响应体
@exceptions.capture
def render_file(file_path, file_name=None):
    ...

```

## 五、实战异常处理模块
既然是异常处理的实战，那我们的逻辑就是故意让程序出错，比如 `RequireReadPermissionError` 这个需要文件可读权限的异常，这次测试的视图是 `Download`，作为一个返回文件的视图，我们这里故意返回一个实验楼用户环境没有读权限的文件，比如 `/etc/shadow` 这个文件，代码如下，定义在 `main.py` 中
```python
...

class Download(BaseView):
    def get(self, request):
        return render_file("/etc/shadow)

...

syl_url_map = {
    ...
    {
        'url': '/download',
        'view': Download,
        'endpoint': 'download'
    },
    ...
}

```

然后再实战一下 `exceptions` 包中的 `reload` 重载异常装饰器，测试代码如下，定义在 `main.py` 中

```python
from sylfk import exceptions
...


@exceptions.reload(404)
def test_reload():
    return '<h1>测试重载 404 异常</h1>'
...
```

运行
```bash
python3 main.py
```

再次访问“/download”页面，发现返回了没有读权限的异常响应体内容
![](no_read.png)

然后测试随笔输入一个不存在的 `URL`，可以看到重载 `404` 异常成功
![](404_reload.png) 


## 六、总结
本节是框架所有模块的最后一节，至此，我们整个框架已经真正的开发完毕了，如果还有想要添加的功能或者模块，欢迎跟我一起交流，帮助同学们一起去实现去扩展，下一节我们就对框架开发所学的课程的知识点进行总结，对后续框架维护方法的讲解。


